# Tradfri color_temp must be between 250 and 454
# 20 min sunrise, (453 -> 250 or 667 -> 182) and 0 -> 255 in 2 stages
# Stage 1: 14 min, 
#   tradfri: brightness 0 -> 255
#   LIFX: brightness 0 -> 170, color_temp 667 -> 344
# Stage 2: 6 min 
#   tradfri: color_temp 453 -> 250
#   LIFX: brightness 170 -> 255, color_temp 344 -> 182
#   hue: just turn on 182 mireds at 255 brightness

# The sunrise sequence is split into stages because the tradfri can't 
# transition color_temp and brightness at the same time
- alias: 'sunrise init'
  trigger:
    platform: time
    at: "07:39:00"
    #at: "06:39:00"
    #at: "05:24:00"
  action:
    # Turn on the LIFX light initial (dim) state
    - service: light.turn_on
      data:
        entity_id: light.lamp
        rgb_color: [255, 200, 0]
        brightness: 30
- alias: 'sunrise stage 1'
  trigger:
    platform: time
    at: "07:39:05"
    #at: "06:39:05"
    #at: "05:24:05"
  action:
    # Turn on the tradfri lights to initial (dim) state
    - service: light.turn_on
      data:
        entity_id: group.tradfri
        color_temp: 453
        brightness: 50
    # Transition stage 1
    - service: light.turn_on
      data:
        entity_id: group.tradfri
        brightness: 255
        transition: 840 # 14 min
    - service: light.lifx_set_state
      data:
        entity_id: light.lamp
        color_temp: 182
        brightness: 255
        # 1200 seconds = 20 min
        transition: 1200
- alias: 'sunrise test stage 2'
  trigger:
    platform: time
    at: "07:55:00"
    #at: "06:55:00"
    #at: "05:40:00"
  action:
      service: light.turn_on
      data:
        entity_id: group.tradfri
        color_temp: 250
        transition: 360 # 6 min
# old below
#- alias: 'sunrise start'
#  trigger:
#    platform: time
#    at: "06:45:00"
#  action:
#    service: light.turn_on
#    data:
#      entity_id: light.lamp
#- alias: 'sunrise sequence'
#  trigger:
#    platform: time
#    at: "06:46:00"
#  action:
#    service: light.lifx_set_state
#    data:
#      entity_id: light.lamp
#      color_temp: 182
#      brightness: 255
#      # 900 seconds = 15 min
#      transition: 900

### Triggering Frontend Themes
- alias: 'startup theme'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: pmxmonolight
# set theme is not working, for some reason
- alias: 'select theme'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.frontend_theme
  action:
    service: frontend.set_theme
    data_template:
      name: "{{ states.input_select.frontend_theme.state }}"


## Turn the tower light on and off when the motion sensor triggers
- alias: 'Motion Sensor ON'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bathroom1
    data:
      color_temp: 500
      transition: 10
      brightness: 10

- alias: 'Motion Sensor OFF'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor
    to: 'off'
    for:
      seconds: 10
  action:
    service: light.turn_off
    entity_id: light.bathroom1
    data:
      transition: 10
