# Tradfri color_temp must be between 250 and 454
- alias: 'set to evening'
  trigger:
    platform: time
    at: "17:13:00"
  action:
    service: scene.turn_on
    entity_id: scene.evening
- alias: 'sunrise test'
  trigger:
    platform: time
    at: "16:03:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom2
        color_temp: 453
        brightness: 50
    - service: light.turn_on
      data:
        entity_id: light.bathroom2
        color_temp: 250
        #brightness: 255
        transition: 20
- alias: 'set state test1'
  trigger:
    platform: time
    at: "16:27:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.entry2
        color_temp: 250
        brightness: 200
    - service: light.turn_off
      data:
        entity_id: light.entry2
- alias: 'set state test2'
  trigger:
    platform: time
    at: "16:27:01"
  action:
    - service: light.turn_off
      data:
        entity_id: light.entry2
- alias: 'sunrise start'
  trigger:
    platform: time
    at: "06:45:00"
  action:
    service: light.turn_on
    data:
      entity_id: light.lamp
- alias: 'sunrise sequence'
  trigger:
    platform: time
    at: "06:46:00"
  action:
    service: light.lifx_set_state
    data:
      entity_id: light.lamp
      color_temp: 182
      brightness: 255
      # 900 seconds = 15 min
      transition: 900
- alias: 'set afternoon hue'
  trigger:
    platform: time
    at: "14:00:00"
  action:
    service: light.lifx_set_state
    data:
      entity_id: light.lamp
      color_temp: 300
      brightness: 80
- alias: 'set evening hue'
  trigger:
    platform: time
    at: "17:30:00"
  action:
    service: light.lifx_set_state
    data:
      entity_id: light.lamp
      color_temp: 350 
      brightness: 50
- alias: 'set bedtime hue'
  trigger:
    platform: time
    at: "21:00:00"
  action:
    service: light.lifx_set_state
    data:
      entity_id: light.lamp
      color_temp: 667
      brightness: 30
